### ISSUE TITLE
System fields "key_id" and "id" are not passed to Emarsys

### ISSUE THREAD

**Issue by tim-bezhashvyly** [snowcap/Emarsys#11]
In case of email change email field (ID = 3) can not be used as identified. In this case internal Emarsys ID has to be obtained and used as identifier. In order to do so two fields "key_id" and "id" have to be added to data set. However `\Snowcap\Emarsys\Client::getFieldId` method throws `Unrecognized field name "%s"` exception as it can't translate these fields into IDs.

**Comment by Moinax** [comment]
You are right,  can you add them to the default mapping ?

**Comment by tim-bezhashvyly** [comment]
I don't think it will work with default mapping as field key is supposed to be numeric.

**Comment by Moinax** [comment]
I don't understand, can we simply add them to the fields.ini file with the right Emarsys ids ?

**Comment by tim-bezhashvyly** [comment]
This is the thing. If I understand everything correctly these fields have no IDs and has to be sent as text. At least it what Emarsys support told (I tested it and it works but I definitely have to write an integration test for it).

**Comment by Moinax** [comment]
Ok, it's been a while since I read the Emarsys documentation.

If it works, we can simply stop casting all ids to integer, otherwise we can maybe add optional arguments  (id, key_id)  to the updateContact method.

I let you find the best solution.

Regards,

**Comment by tim-bezhashvyly** [comment]
I wold would prefer to leave my implementation with just keeping the list of system keys (see link to commit above in this thread).

It is also included into the pull request #12.

**Comment by Moinax** [comment]
Ho yeah, I didn't see what you did there, it seems pretty ok for me :)
