### ISSUE TITLE
Delete Contact end point is not implemented

### ISSUE THREAD

**Issue by pirvulescu** [snowcap/Emarsys#26]
Delete contact end point is not implemented: http://documentation.emarsys.com/resource/developers/endpoints/contacts/delete-contact/

You should just add the next code to the Client class:

     /** delete a contact
     * @param array $params
     *
     * @return Response
     */
    public function deleteContact($params){
        return $this->send(HttpClient::POST, 'contact/delete', $params);
    }

**Comment by Moinax** [comment]
Hi @pirvulescu,

Can you please do a pull request ?

Thank you in advance,

Regards

**Comment by pirvulescu** [comment]
I tried, but I have no access. 

Dan

**Comment by tim-bezhashvyly** [comment]
No worries, I will do it.

**Comment by Moinax** [comment]
Nice job guys 👍 

Thanks for your help to keep this repo up to date :-)

Regards
