### ISSUE TITLE
New versions unavailabel at packagist

### ISSUE THREAD

**Issue by webarchitect609** [snowcap/Emarsys#30]
New versions v.1.1.0 and v.1.2.0 unavailabel at packagist. 
Please, compare http://joxi.ru/1A5p9Gfnn3Pg2E?d=1 and http://joxi.ru/4AkeOlfyygg1mq?d=1

**Comment by tim-bezhashvyly** [comment]
@Moinax Could you please enable automatic sync at packagist?

**Comment by Moinax** [comment]
I don't understand, this should be the case.

**Comment by tim-bezhashvyly** [comment]
https://packagist.org/about#how-to-update-packages

**Comment by Moinax** [comment]
Yes it's on for while now, I juste test the service and everything seems allright

https://www.dropbox.com/s/8fabdabpk466cgc/Screenshot%202016-11-23%2013.33.45.png?dl=0

It seems the auto-update and the manual update on packagist keep the version to 1.0.7, but I don't know why.

**Comment by webarchitect609** [comment]
I found typos in tags. Watch screenshot, please: http://joxi.ru/v29lJGF33MdMmG?d=1

**Comment by tim-bezhashvyly** [comment]
Good catch. Thank you. Was my fault. Fixed.

**Comment by tim-bezhashvyly** [comment]
1.2.0 is now at packagist.

**Comment by Moinax** [comment]
Nice, you got good eyes :-)
