### ISSUE TITLE
CURLOPT_CONNECTTIMEOUT and CURLOPT_TIMEOUT not set

### ISSUE THREAD

**Issue by pirvulescu** [snowcap/Emarsys#33]
Hi, 

I think it is better to set values for `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT` in `CurlClient` class. In the case of not response the PHP script crash with execution timeout error.

Dan

**Comment by Moinax** [comment]
Hi,

This is not a bad idea. Can your make a PR for this ?

Thanks for your help

**Comment by pirvulescu** [comment]
As I said before, I have no right to make a pull request. Please give me the access and I will create one :).

**Comment by tim-bezhashvyly** [comment]
Anyone can do a pull request. You have to fork repo first.

**Comment by boogie** [comment]
Here's the article about it: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by pirvulescu** [comment]
I tried directly from the local machine. I'll do it from fork. 
Thanks

**Comment by tim-bezhashvyly** [comment]
Fixed via #45.

**Comment by Moinax** [comment]
Thanks @mehabox for this fix and @tim-bezhashvyly for your help on merging this 👍
