### ISSUE TITLE
Response - Invalid result structure

### ISSUE THREAD

**Issue by Ossama8** [snowcap/Emarsys#41]
`$response = $client->createContact($data);`       
`$response = (array)$response;`
`$obj = new Response($response);`
`echo '<pre>'; print_r( $obj->getReplyCode() ); echo '</pre>'; die('Call');`

ClientException in Response.php line 39: Invalid result structure

How to solve this ? I download it today.

**Comment by Ossama8** [comment]
When I changed Response.php variable **protected to private**, it return response correctly. What should I do ? Should I go with Public or is there any other solution for Protected ?

```
use Snowcap\Emarsys\Exception\ClientException;

class Response
{
    const REPLY_CODE_OK = 0;
    const REPLY_CODE_INTERNAL_ERROR = 1;
    const REPLY_CODE_INVALID_KEY_FIELD = 2004;
    const REPLY_CODE_MISSING_KEY_FIELD = 2005;
    const REPLY_CODE_CONTACT_NOT_FOUND = 2008;
    const REPLY_CODE_NON_UNIQUE_RESULT = 2010;
    const REPLY_CODE_INVALID_STATUS = 6003;
    const REPLY_CODE_INVALID_DATA = 10001;

    /**
     * @var int
     */
    public $replyCode;
    /**
     * @var string
     */
    public $replyText;
    /**
     * @var array
     */
    public $data = array();
```

**Comment by Ossama8** [comment]
If you replace by protected to public it will not return **invalid**

**Comment by pradeep-rajapaksha** [comment]
You cannot modify the *Response.php* (/vendor/snowcap/emarsys/src/Snowcap/Emarsys/Response.php) which in the package since it isn't the best practice. 

But, you can overwrite that class by your own class. unless your changes will be lost when package updated whenever.

**Comment by tim-bezhashvyly** [comment]
Closing as not enough data on what author is trying to achieve.
