### ISSUE TITLE
Integrate license informations

### ISSUE THREAD

**Issue by sem4711** [snowcap/Emarsys#52]
Hi guys,

I have tested your repository and found it to be good. I would like to use it for an own project. Legally speaking, however, I am not allowed to do so, nor is anyone else in this world. 

Why that? You have not included any license information in the project. Please make sure to add this good library, so that I and everybody else can legally use it.

These pages will help you to integrate quickly into your github project:
[https://help.github.com/](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)
[https://choosealicense.com/ ](https://choosealicense.com/ )

**Comment by Moinax** [comment]
Thanks for your comment, I totally forgot about this when I created this library a while ago.

I added the MIT license on it.

Regards

**Comment by sem4711** [comment]
Hello Jérôme,

well done - I thank you for your rapid support!

/sem
